export default {
    LOAD_PROFILE_POSTS: 'LOAD_PROFILE_POSTS',
    LOAD_PROFILE_POSTS_SUCCESS: 'LOAD_PROFILE_POSTS_SUCCESS',
    LOAD_PROFILE_POSTS_ERROR: 'LOAD_PROFILE_POSTS_ERROR',

    REQUEST_OPEN_POST_MODAL: 'REQUEST_OPEN_POST_MODAL',
    OPEN_POST_MODAL: 'OPEN_POST_MODAL',
    CLOSE_POST_MODAL: 'CLOSE_POST_MODAL',

    POST_COMMENT: 'POST_COMMENT',
    POST_COMMENT_SUCCESS: 'POST_COMMENT_SUCCESS',
    POST_COMMENT_ERROR: 'POST_COMMENT_ERROR',

    DELETE_COMMENT: 'DELETE_COMMENT',
    DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
    DELETE_COMMENT_ERROR: 'DELETE_COMMENT_ERROR',

    LIKE_POST: 'LIKE_POST',
    LIKE_POST_SUCCESS: 'LIKE_POST_SUCCESS',
    LIKE_POST_ERROR: 'LIKE_POST_ERROR',

    DELETE_LIKE: 'DELETE_LIKE',
    DELETE_LIKE_SUCCESS: 'DELETE_LIKE_SUCCESS',
    DELETE_LIKE_ERROR: 'DELETE_LIKE_ERROR',
};