const prefix = '@@user/';

export default {
    SIGN_IN: `${prefix}SIGN_IN`,
    SIGN_IN_SUCCESS: `${prefix}SIGN_IN_SUCCESS`,
    SIGN_IN_ERROR: `${prefix}SIGN_IN_ERROR`,

    SIGN_UP: `${prefix}SIGN_UP`,
    SIGN_UP_SUCCESS: `${prefix}SIGN_UP_SUCCESS`,
    SIGN_UP_ERROR: `${prefix}SIGN_UP_ERROR`,

    LOGOUT: `${prefix}LOGOUT`,

    UNAUTHORIZED: `${prefix}UNAUTHORIZED`,

    CONFIRM_CODE: `${prefix}CONFIRM_CODE`,
    CONFIRM_CODE_SUCCESS: `${prefix}CONFIRM_CODE_SUCCESS`,
    CONFIRM_CODE_ERROR: `${prefix}CONFIRM_CODE_ERROR`,

    CONFIRM_RESET_PASSWORD: `${prefix}CONFIRM_RESET_PASSWORD`,
    CONFIRM_RESET_PASSWORD_SUCCESS: `${prefix}CONFIRM_RESET_PASSWORD_SUCCESS`,
    CONFIRM_RESET_PASSWORD_ERROR: `${prefix}CONFIRM_RESET_PASSWORD_ERROR`,

    RESET_PASSWORD: `${prefix}RESET_PASSWORD`,
    RESET_PASSWORD_SUCCESS: `${prefix}RESET_PASSWORD_SUCCESS`,
    RESET_PASSWORD_ERROR: `${prefix}RESET_PASSWORD_ERROR`,

    CHANGE_PASSWORD: `${prefix}CHANGE_PASSWORD`,
    CHANGE_PASSWORD_SUCCESS: `${prefix}CHANGE_PASSWORD_SUCCESS`,
    CHANGE_PASSWORD_ERROR: `${prefix}CHANGE_PASSWORD_ERROR`,
};