export default {
    USER_SIGN_IN: 'USER_SIGN_IN',
    USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
    USER_SIGN_IN_ERROR: 'USER_SIGN_IN_ERROR',

    USER_SIGN_UP: 'USER_SIGN_UP',
    USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
    USER_SIGN_UP_ERROR: 'USER_SIGN_UP_ERROR',

    USER_LOGOUT: 'USER_LOGOUT',

    USER_UNAUTHORIZED: 'USER_UNAUTHORIZED',

    CONFIRM_EMAIL: 'CONFIRM_EMAIL',
    CONFIRM_EMAIL_SUCCESS: 'CONFIRM_EMAIL_SUCCESS',
    CONFIRM_EMAIL_ERROR: 'CONFIRM_EMAIL_ERROR',

    CONFIRM_RESET_PASSWORD: 'CONFIRM_RESET_PASSWORD',
    CONFIRM_RESET_PASSWORD_SUCCESS: 'CONFIRM_RESET_PASSWORD_SUCCESS',
    CONFIRM_RESET_PASSWORD_ERROR: 'CONFIRM_RESET_PASSWORD_ERROR',

    RESET_PASSWORD: 'RESET_PASSWORD',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',

};