export default {
    //sign in
    USER_SIGN_IN: 'USER_SIGN_IN',
    USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
    USER_SIGN_IN_ERROR: 'USER_SIGN_IN_ERROR',

    //sing up
    USER_SIGN_UP: 'USER_SIGN_UP',
    USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
    USER_SIGN_UP_ERROR: 'USER_SIGN_UP_ERROR',

    //log out
    USER_LOGOUT: 'USER_LOGOUT',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR',
};