const prefix = '@@post/';

export default {
    OPEN_DETAIL_MODAL: `${prefix}OPEN_DETAIL_MODAL`,
    CLOSE_DETAIL_MODAL: `${prefix}CLOSE_DETAIL_MODAL`,

    LOAD_DETAIL_DATA: `${prefix}LOAD_DETAIL_DATA`,
    LOAD_DETAIL_DATA_SUCCESS: `${prefix}LOAD_DETAIL_DATA_SUCCESS`,
    LOAD_DETAIL_DATA_ERROR: `${prefix}LOAD_DETAIL_DATA_ERROR`,

    LOAD_PROFILE_POSTS: `${prefix}LOAD_PROFILE_POSTS`,
    LOAD_PROFILE_POSTS_SUCCESS: `${prefix}LOAD_PROFILE_POSTS_SUCCESS`,
    LOAD_PROFILE_POSTS_ERROR: `${prefix}LOAD_PROFILE_POSTS_ERROR`,

    LOAD_FOLLOWING_POSTS: `${prefix}LOAD_FOLLOWING_POSTS`,
    LOAD_FOLLOWING_POSTS_SUCCESS: `${prefix}LOAD_FOLLOWING_POSTS_SUCCESS`,
    LOAD_FOLLOWING_POSTS_ERROR: `${prefix}LOAD_FOLLOWING_POSTS_ERROR`,

    POST_COMMENT: `${prefix}POST_COMMENT`,
    POST_COMMENT_SUCCESS: `${prefix}POST_COMMENT_SUCCESS`,
    POST_COMMENT_ERROR: `${prefix}POST_COMMENT_ERROR`,

    DELETE_COMMENT: `${prefix}DELETE_COMMENT`,
    DELETE_COMMENT_SUCCESS: `${prefix}DELETE_COMMENT_SUCCESS`,
    DELETE_COMMENT_ERROR: `${prefix}DELETE_COMMENT_ERROR`,

    POST_LIKE: `${prefix}POST_LIKE`,
    POST_LIKE_SUCCESS: `${prefix}POST_LIKE_SUCCESS`,
    POST_LIKE_ERROR: `${prefix}POST_LIKE_ERROR`,

    DELETE_LIKE: `${prefix}DELETE_LIKE`,
    DELETE_LIKE_SUCCESS: `${prefix}DELETE_LIKE_SUCCESS`,
    DELETE_LIKE_ERROR: `${prefix}DELETE_LIKE_ERROR`,

};