const prefix = '@@profile/';

export default {
    LOAD_VIEW_DATA: `${prefix}LOAD_VIEW_DATA`,
    LOAD_VIEW_DATA_SUCCESS: `${prefix}LOAD_VIEW_DATA_SUCCESS`,
    LOAD_VIEW_DATA_ERROR: `${prefix}LOAD_VIEW_DATA_ERROR`,

    LOAD_EDIT_DATA: `${prefix}LOAD_EDIT_DATA`,
    LOAD_EDIT_DATA_SUCCESS: `${prefix}LOAD_EDIT_DATA_SUCCESS`,
    LOAD_EDIT_DATA_ERROR: `${prefix}LOAD_EDIT_DATA_ERROR`,

    UPDATE_IMAGE: `${prefix}UPDATE_IMAGE`,
    UPDATE_IMAGE_SUCCESS: `${prefix}UPDATE_IMAGE_SUCCESS`,
    UPDATE_IMAGE_ERROR: `${prefix}UPDATE_IMAGE_ERROR`,

    UPDATE: `${prefix}UPDATE`,
    UPDATE_SUCCESS: `${prefix}UPDATE_SUCCESS`,
    UPDATE_ERROR: `${prefix}UPDATE_ERROR`,

    LOAD_AVATAR: `${prefix}LOAD_AVATAR`,
    LOAD_AVATAR_SUCCESS: `${prefix}LOAD_AVATAR_SUCCESS`,
    LOAD_AVATAR_ERROR: `${prefix}LOAD_AVATAR_ERROR`,

    FOLLOW: `${prefix}FOLLOW`,
    FOLLOW_SUCCESS: `${prefix}FOLLOW_SUCCESS`,
    FOLLOW_ERROR: `${prefix}FOLLOW_ERROR`,

    UNFOLLOW: `${prefix}UNFOLLOW`,
    UNFOLLOW_SUCCESS: `${prefix}UNFOLLOW_SUCCESS`,
    UNFOLLOW_ERROR: `${prefix}UNFOLLOW_ERROR`,
};