
export default {
    LOAD_VIEW_PROFILE_DATA: 'LOAD_VIEW_PROFILE_DATA',
    LOAD_VIEW_PROFILE_DATA_SUCCESS: 'LOAD_VIEW_PROFILE_DATA_SUCCESS',
    LOAD_VIEW_PROFILE_DATA_ERROR: 'LOAD_VIEW_PROFILE_DATA_ERROR',

    LOAD_EDIT_PROFILE_DATA: 'LOAD_EDIT_PROFILE_DATA',
    LOAD_EDIT_PROFILE_DATA_SUCCESS: 'LOAD_EDIT_PROFILE_DATA_SUCCESS',
    LOAD_EDIT_PROFILE_DATA_ERROR: 'LOAD_EDIT_PROFILE_DATA_ERROR',

    UPDATE_PROFILE_IMAGE: 'UPDATE_PROFILE_IMAGE',
    UPDATE_PROFILE_IMAGE_SUCCESS: 'UPDATE_PROFILE_IMAGE_SUCCESS',
    UPDATE_PROFILE_IMAGE_ERROR: 'UPDATE_PROFILE_IMAGE_ERROR',

    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',

    LOAD_PROFILE_AVATAR: 'LOAD_PROFILE_AVATAR',
    LOAD_PROFILE_AVATAR_SUCCESS: 'LOAD_PROFILE_AVATAR_SUCCESS',
    LOAD_PROFILE_AVATAR_ERROR: 'LOAD_PROFILE_AVATAR_ERROR',

    CHANGE_FOLLOWING: 'CHANGE_FOLLOWING',
    CHANGE_FOLLOWING_SUCCESS: 'CHANGE_FOLLOWING_SUCCESS',
    CHANGE_FOLLOWING_ERROR: 'CHANGE_FOLLOWING_ERROR',

};