
export default {
    LOAD_VIEW_PROFILE_DATA: 'LOAD_VIEW_PROFILE_DATA',
    LOAD_VIEW_PROFILE_DATA_SUCCESS: 'LOAD_VIEW_PROFILE_DATA_SUCCESS',
    LOAD_VIEW_PROFILE_DATA_ERROR: 'LOAD_VIEW_PROFILE_DATA_ERROR',

    LOAD_EDIT_PROFILE_DATA: 'LOAD_EDIT_PROFILE_DATA',
    LOAD_EDIT_PROFILE_DATA_SUCCESS: 'LOAD_EDIT_PROFILE_DATA_SUCCESS',
    LOAD_EDIT_PROFILE_DATA_ERROR: 'LOAD_EDIT_PROFILE_DATA_ERROR',

    UPDATE_PROFILE_IMAGE: 'UPDATE_PROFILE_IMAGE',
    UPDATE_PROFILE_IMAGE_SUCCESS: 'UPDATE_PROFILE_IMAGE_SUCCESS',
    UPDATE_PROFILE_IMAGE_ERROR: 'UPDATE_PROFILE_IMAGE_ERROR',

    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',

    LOAD_PROFILE_AVATAR: 'LOAD_PROFILE_AVATAR',
    LOAD_PROFILE_AVATAR_SUCCESS: 'LOAD_PROFILE_AVATAR_SUCCESS',
    LOAD_PROFILE_AVATAR_ERROR: 'LOAD_PROFILE_AVATAR_ERROR',

    FOLLOW: 'FOLLOW',
    FOLLOW_SUCCESS: 'FOLLOW_SUCCESS',
    FOLLOW_ERROR: 'FOLLOW_ERROR',

    UNFOLLOW: 'UNFOLLOW',
    UNFOLLOW_SUCCESS: 'UNFOLLOW_SUCCESS',
    UNFOLLOW_ERROR: 'UNFOLLOW_ERROR',

    LOAD_FOLLOWERS: 'LOAD_FOLLOWERS',
    LOAD_FOLLOWERS_SUCCESS: 'LOAD_FOLLOWERS_SUCCESS',
    LOAD_FOLLOWERS_ERROR: 'LOAD_FOLLOWERS_ERROR',

    LOAD_FOLLOWING: 'LOAD_FOLLOWING',
    LOAD_FOLLOWING_SUCCESS: 'LOAD_FOLLOWING_SUCCESS',
    LOAD_FOLLOWING_ERROR: 'LOAD_FOLLOWING_ERROR',

    OPEN_UNFOLLOW_MODAL: 'OPEN_UNFOLLOW_MODAL',
    CLOSE_UNFOLLOW_MODAL: 'CLOSE_UNFOLLOW_MODAL'
};